In [1]:
import pandas as pd 
import seaborn as sns

In [2]:
films= pd.read_csv('filmtv_movies.csv')

In [3]:
films.head()

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0

In [4]:
films['genre'].unique()

array(['Animation', 'Drama', 'Romantic', 'Comedy', 'Spy', 'Crime',
       'Thriller', 'Adventure', 'Documentary', 'Horror', 'Action',
       'Western', 'Biography', 'Musical', 'Sci-Fi', 'War', 'Grotesque',
       'Gangster', 'Fantasy', 'MÃ©lo', 'Mythology', 'History', 'Erotico',
       'Noir', 'Super-hero', 'Biblical', 'Sport', 'Sperimental', nan,
       'Short Movie', 'Stand-up Comedy'], dtype=object)

In [5]:
map = {names:i for i,names in enumerate(films['genre'].unique())}

films['genre'] = films['genre'].replace(map)

C:\Users\szymo\AppData\Local\Temp\ipykernel_21512\911496928.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  films['genre'] = films['genre'].replace(map)

In [6]:
films['country']= films['country'].str.split(',').str[0]

In [7]:
mapCountry = {names:i for i, names in enumerate(films['country'].unique())}
films['country'] = films['country'].replace(mapCountry)

C:\Users\szymo\AppData\Local\Temp\ipykernel_21512\1728329494.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  films['country'] = films['country'].replace(mapCountry)

In [8]:
unique_names =films['directors'].unique()
name_to_value = {name: i for i, name in enumerate(unique_names)}

films['directors'] = films['directors'].map(name_to_value)

In [9]:
films.head()

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,0,76,0,0,NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0
1,3,18 anni tra una settimana,1991,1,98,1,1,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
2,17,Ride a Wild Pony,1976,2,91,0,2,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
3,18,Diner,1982,3,95,0,3,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
4,20,A che servono questi quattrini?,1942,3,85,1,4,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0

In [10]:
def PolecajkaFilmowaDirichlet(titl:str):
    filmRow = films[films['title'] == titl ]
    if len(filmRow) == 0:
        return "Movie not found"
    movies = films.drop(filmRow.index)

    filmYear = filmRow['year'].values
    filmCountry = filmRow['country'].values
    filmDirector = filmRow['directors'].values
    filmGenre = filmRow['genre'].values

    filmDist = movies['year'].values - filmYear
    countryDist = movies['country'].values - filmCountry
    directorDist = movies['directors'].values - filmDirector
    genreDist = movies['genre'].values - filmGenre
    
    moviesRecomend = movies

    #Dirichlet's metric 

    moviesRecomend['year'] = moviesRecomend['year'].apply(lambda x: 1 if x != 0 else 0) 
    moviesRecomend['country'] = moviesRecomend['country'].apply(lambda x: 1 if x != 0 else 0)
    moviesRecomend['directors'] = moviesRecomend['directors'].apply(lambda x: 1 if x != 0 else 0)
    moviesRecomend['genre'] = moviesRecomend['genre'].apply(lambda x: 1 if x != 0 else 0)

    moviesRecomend['summary'] = moviesRecomend['year'] + moviesRecomend['country'] + moviesRecomend['directors'] + moviesRecomend['genre']

    bestRecomendation = moviesRecomend['summary'].sort_values(ascending=True)

    bestFilmIndex = bestRecomendation.index[0]

    bestFilm = moviesRecomend['title'][0]

    return bestFilm

In [11]:
PolecajkaFilmowaDirichlet('Diner')

"Bugs Bunny's Third Movie: 1001 Rabbit Tales"

ML ver without description

In [12]:
films.head()

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,0,76,0,0,NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0
1,3,18 anni tra una settimana,1991,1,98,1,1,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
2,17,Ride a Wild Pony,1976,2,91,0,2,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
3,18,Diner,1982,3,95,0,3,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
4,20,A che servono questi quattrini?,1942,3,85,1,4,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0

In [16]:
films['actorsSplit'] = films['actors'].str.split(',')
films['actorsLen'] = films['actorsSplit'].apply(lambda x: len(x) if isinstance(x, list) else 0)
films['actorsLen'] = films['actorsLen'].fillna(0)
maxActors = films.loc[films['actorsLen'].idxmax()]
filmsActors = pd.DataFrame(films['actors'].to_list())

In [17]:
maxActors['actorsLen']

89

In [15]:
def PolecajkaFilmowaNN(titl:str):
    pass